### ISSUE TITLE
Serilog dynamic console not working as expected with Steeltoe 3.0 packages

### ISSUE THREAD

**Issue by sajanep** [SteeltoeOSS/Steeltoe#462]
Hi,
I just updated steeltoe packages to 3.0.0(was using 2.4.3 before). When I run the application, I am getting below error. Please note that I am using serilog dynamic console and looks like latest version available is 2.5.0.

System.TypeLoadException: 'Could not load type 'Steeltoe.Extensions.Logging.IDynamicLoggerProvider' from assembly 'Steeltoe.Extensions.Logging.DynamicLogger, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.'

My Program.cs looks like below

```
public class Program
    {

        /// <summary>
        /// Main 
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static void Main(string[] args)
        {
            Activity.DefaultIdFormat = ActivityIdFormat.W3C;

            CreateHostBuilder(args).Build().Run();
        }

        /// <summary>
        /// CreateHostBuilder
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostContext, configApp) =>
                {
                    configApp.AddCloudFoundry();
                })
                .ConfigureLogging((builderContext, loggingBuilder) =>
                {
                    loggingBuilder.ClearProviders();
                    loggingBuilder.AddSerilogDynamicConsole();
                })
                .AddCloudFoundryActuators()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```
My .csproj looks like below

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Update="wwwroot\**\*;*.yml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Steeltoe.Extensions.Logging.SerilogDynamicLogger" Version="2.5.0" />
    <PackageReference Include="Steeltoe.Management.CloudFoundryCore" Version="3.0.0" />
    <PackageReference Include="Steeltoe.Extensions.Configuration.CloudFoundryCore" Version="3.0.0" />
  </ItemGroup>
</Project>
```

**Comment by TimHess** [comment]
`Steeltoe.Extensions.Logging.SerilogDynamicLogger` was one of a few [packages renamed in 3.0](https://steeltoe.io/docs/3/welcome/whats-new#package-name-changes), depending on your needs you can use either `Steeltoe.Extensions.Logging.DynamicSerilogBase` or `Steeltoe.Extensions.Logging.DynamicSerilogCore`

**Comment by sajanep** [comment]
Hello,
I updated the package to Steeltoe.Extensions.Logging.DynamicSerilogCore and I am able to build and deploy application to PCF. But unfortunately logs are not coming in serilog format. I do have the serilog configuration in my appsettings as well.

```
{
  "management": {
    "endpoints": {
      "path": "/myexample/cloudfoundryapplication",
      "cloudfoundry": {
        "validateCertificates": false
      },
      "actuator": {
        "exposure": {
          "include": [ "*" ],
          "exclude": [ "env", "refresh" ]
        }
      }
    }
  },

  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Information",
        "Steeltoe": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "Console",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext}: {Properties} {NewLine} {EventId} {Message:lj}{NewLine}{Exception}"
        }
      },
      {
        "Name": "Trace",
        "Args": {
          "outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext}: {Properties} {NewLine} {EventId} {Message:lj}{NewLine}{Exception}"
        }
      }
    ],
    "Enrich": [ "FromLogContext" ]
  }
}
```
Program.cs is like below

```
public static class Program
    {

        /// <summary>
        /// Main 
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static void Main(string[] args)
        {
            Activity.DefaultIdFormat = ActivityIdFormat.W3C;
            CreateHostBuilder(args).Build().Run();
        }


        /// <summary>
        /// CreateHostBuilder
        /// </summary>
        /// <param name="args"></param>
        /// <returns></returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .AddCloudFoundryConfiguration()
                .ConfigureLogging((builderContext, loggingBuilder) =>
                {
                    // Add Serilog Dynamic Logger 
                    loggingBuilder.AddDynamicSerilog();
                })
                .AddCloudFoundryActuators()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```
.csproj looks ike below

 ```
 <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Update="wwwroot\**\*;*.yml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Trace" Version="2.1.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="1.1.0" />
    <PackageReference Include="Steeltoe.Extensions.Logging.DynamicSerilogCore" Version="3.0.1" />
    <PackageReference Include="Steeltoe.Management.CloudFoundryCore" Version="3.0.1" />
    <PackageReference Include="Steeltoe.Extensions.Configuration.CloudFoundryCore" Version="3.0.1" />
  </ItemGroup>

</Project>

```
Please note that this used to work with steeltoe 2.4.3 packages. Not sure what happened when I migrated to 3.0.1

**Comment by sajanep** [comment]
Do I need to open a new issue? Can someone point me to a working sample which demonstrates the usage of Steeltoe.Extensions.Logging.DynamicSerilogCore

**Comment by TimHess** [comment]
We can just work with this issue for now... The functionality does not appear to match up with how the docs describe it. We'll have to dig in to see if there's some code change(s) we can/should do here, or if it is just a documentation issue, but it looks like the console sink doesn't get configured in Steeltoe code.

I think the changes here were intended as an enhancement (use more of Serilog capability than only writing to console). We provide a simple hook so you can add whatever you want, here's how to add the console sink:

`.AddDynamicSerilog((context, serilogConfig) => serilogConfig.WriteTo.Console())`

**Comment by sajanep** [comment]
> I think the changes here were intended as an enhancement (use more of Serilog capability than only writing to console). We provide a simple hook so you can add whatever you want, here's how to add the console sink:
> 
> `.AddDynamicSerilog((context, serilogConfig) => serilogConfig.WriteTo.Console())`

Thanks for looking into this. Bit looks like hook is not available for `IHostBuilder` as I am getting a compilation error.

**Comment by TimHess** [comment]
That hook is on `IHostBuilder`, but looking at your original code again, it looks like you are (or at least were) configuring logging inside `ConfigureLogging`. In that case you need to provide the SerilogConfig directly instead of via the action, so more like `.AddDynamicSerilog(new LoggerConfiguration().WriteTo.Console())`
